version: '3'

services:
    web:
      image: node:11
      environment:
        - HUNKBOTEMAIL=hunkbot@use.startmail.com
        - HUNKBOTPASSWORD=vainglory2876
        - HUNKBOTUSERNAME=hunkbot
        - IMAGEPATH=./images/
        - HOSTPATH=https://justincameron.org/hunkbot/
